spring.application.name=HMS

spring.datasource.username=Root
spring.datasource.password=Asiya

spring.datasource.url=jdbc:h2:mem:HMS
spring.datasource.driverClassName=org.h2.Driver

spring.datasource.show-sql=true
spring.jpa.hibernate.ddl-auto=update
